name: mandal_variety
description: "Local grocery and daily essentials delivery app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/logo/mandal_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/mandal_logo.png"
  adaptive_icon_foreground: "assets/logo/mandal_logo.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
